sudo: required
dist: trusty

script:
  - sudo apt-get install linux-headers-$(uname -r)
  - git clone https://github.com/citueda/RaspberryPiMouse.git 
  - cd RaspberryPiMouse/utils
  - sudo bash ./build_install.ubuntu14.bash
  - cd ../../
  - sudo bash -evx ./setup.bash
