sudo: required
dist: trusty

script:
  - sudo crontab ./crontab.conf
  - git clone https://github.com/citueda/RaspberryPiMouse.git 
  - cd RaspberryPiMouse/utils
  - sudo bash ./build_install.ubuntu14.bash
  - sudo reboot
  - ls /dev/rt*
