sudo: required
dist: trusty

script:
  - sudo apt-get install linux-headers-$(uname -r)
  - cd ..
  - git clone https://github.com/citueda/RaspberryPiMouse.git 
  - cd RaspberryPiMouse/utils
  - sudo bash ./build_install.ubuntu14.bash
  - cd ../../raspimouse_setup
  - sudo bash -evx ./setup.bash
  - bash -evx ./test/travis_test.bash
